### ISSUE TITLE
Breaks with node version 12

### ISSUE THREAD

**Issue by SISheogorath** [ml1nk/node-scrypt#11]
We just wanted to [add node version 12 n our CI chain](https://github.com/codimd/server/pull/65) and had to notice that scrypt broke compatibility with node 12. Is there any intention to make this library compatible with node version 12?

Seems like it simply fails on renamed/changed function names like `v8::Value::IntegerValue()`.

**Comment by ml1nk** [comment]
This fork contains some fixes to the original (long dead) node-scrypt package like [issue 185](https://github.com/barrysteyn/node-scrypt/issues/185) mostly from other contributors. Since scrypt is native to nodejs with [v10.5.0](https://nodejs.org/en/blog/release/v10.5.0/) you should switch to something like [scrypt-kdf](https://github.com/chrisveness/scrypt-kdf) on anything >=10.5.0.

**Comment by SISheogorath** [comment]
Thanks for the hint, we implemented a fix :)

https://github.com/codimd/server/pull/66
