### ISSUE TITLE
RangeError: Scrypt params object 'N' property is out of range

### ISSUE THREAD

**Issue by zadam** [ml1nk/node-scrypt#7]
My N was 16384 and it used to work fine in the old node-scrypt. I traced this to https://github.com/ml1nk/node-scrypt/commit/5d69c3ac85fbd20618d9a248aceb97960edd8879

It seems that behavior changed and N is now actually logN, so what used to be 16384 is now 14 (2^14). This is supported by the fact that when I change N to 14, everything works with hashes generated by the old node-scrypt with N 16384.

Even some of the API examples in the README have N=1024, 16384 etc which would now trigger this range error.

**Comment by ml1nk** [comment]
Since scrypt 1.2.1 there is an assertion which checks that logN is in range. In node-scrypt N was always treated as logN (keyderivation.c). The naming is inconvenient, but it seems using params.N>=256 was never wanted. I changed the README accordingly. 

Can this Issue be closed or have i overseen something?
